name: Render and Lint Documentation

on:
  pull_request:
    branches_ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    name: Linting
    steps:

      - uses: actions/checkout@v3

      - name: Lint
        run: |
          make lint
